# Generated by Django 4.1.13 on 2025-07-08 01:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_client_remove_user_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(accounts.models.UserType['ADMIN'], 'Admin'), (accounts.models.UserType['DISTRIBUTOR'], 'Distributor'), (accounts.models.UserType['RETAILER'], 'Retailer'), (accounts.models.UserType['CLIENT'], 'Client')], default=accounts.models.UserType['CLIENT']),
        ),
    ]
