# Generated by Django 5.2.4 on 2025-07-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=False)),
                ('sms', models.BooleanField(default=False)),
                ('recharge_success', models.BooleanField(default=True)),
                ('recharge_failed', models.BooleanField(default=True)),
                ('new_user_registered', models.BooleanField(default=True)),
                ('low_balance', models.BooleanField(default=True)),
                ('maintenance_scheduled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
